[package]
name = "stoa"
version = "0.1.0"
description = "Stoa — Local-first decentralized collaboration"
authors = ["you"]
edition = "2021"

[lib]
name = "tauri_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
libp2p = { version = "0.56.0", features = ["mdns", "noise", "yamux", "tcp", "tokio", "macros", "ed25519", "request-response", "json"] }
tokio = { version = "1", features = ["full"] }
dirs = "6.0.0"
futures = "0.3"
hex = "0.4"
base64 = "0.22"
rand = "0.8"
uuid = { version = "1", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
sha2 = "0.10"
tauri-plugin-dialog = "2.7.0"
x25519-dalek = { version = "2", features = ["static_secrets"] }
aes-gcm = "0.10"
curve25519-dalek = { version = "4", features = ["digest"] }
