[package]
name = "rust_lib_stoa"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
anyhow = "1.0.102"
flutter_rust_bridge = "=2.12.0"
stoa-node = { version = "0.1.0", path = "stoa-node" }
stoa-messaging = { version = "0.1.0", path = "stoa-messaging" }
tokio = { version = "1.51.0", features = ["sync"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }

[workspace]
members = [
    "stoa-node",
    "stoa-messaging",
]
resolver = "2"
