// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ChatStore>>
abstract class ChatStore implements RustOpaqueInterface {
  void addContact({required String peerId, required String displayName});

  List<ContactEntry> getContacts();

  List<ChatMessage> getMessages({required String topic});

  void insertMessage({required ChatMessage msg});

  factory ChatStore({required String dbPath}) =>
      RustLib.instance.api.crateApiChatChatStoreNew(dbPath: dbPath);

  void removeContact({required String peerId});
}

class ChatMessage {
  final String id;
  final String senderId;
  final String topic;
  final String content;
  final PlatformInt64 timestamp;

  const ChatMessage({
    required this.id,
    required this.senderId,
    required this.topic,
    required this.content,
    required this.timestamp,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      senderId.hashCode ^
      topic.hashCode ^
      content.hashCode ^
      timestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          senderId == other.senderId &&
          topic == other.topic &&
          content == other.content &&
          timestamp == other.timestamp;
}

class ContactEntry {
  final String peerId;
  final String displayName;
  final PlatformInt64 addedAt;

  const ContactEntry({
    required this.peerId,
    required this.displayName,
    required this.addedAt,
  });

  @override
  int get hashCode => peerId.hashCode ^ displayName.hashCode ^ addedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContactEntry &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          displayName == other.displayName &&
          addedAt == other.addedAt;
}
