// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `hex_to_bytes32`

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LanPeerHandle>>
abstract class LanPeerHandle implements RustOpaqueInterface {
  /// Poll for a newly discovered LAN peer. Returns None if no new peer yet.
  Future<LanPeer?> pollPeer();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<StoaCoreNode>>
abstract class StoaCoreNode implements RustOpaqueInterface {
  /// Create a new node with persistent identity.
  /// `data_dir` is the app's document directory.
  static Future<StoaCoreNode> create({required String dataDir}) =>
      RustLib.instance.api.crateApiSimpleStoaCoreNodeCreate(dataDir: dataDir);

  String displayName();

  /// Join a gossip topic. Returns a TopicHandle for send/receive.
  Future<TopicHandle> joinTopic({required String topicHex});

  String nodeId();

  Future<void> setDisplayName({required String name});

  /// Start listening for LAN peers via mDNS. Returns a handle to poll for discoveries.
  Future<LanPeerHandle> subscribeLan();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TopicHandle>>
abstract class TopicHandle implements RustOpaqueInterface {
  Future<GossipMsg?> recvMessage();

  Future<void> sendMessage({required String content});
}

/// A gossip message received from a peer.
class GossipMsg {
  final String content;
  final String sender;

  const GossipMsg({required this.content, required this.sender});

  @override
  int get hashCode => content.hashCode ^ sender.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GossipMsg &&
          runtimeType == other.runtimeType &&
          content == other.content &&
          sender == other.sender;
}

/// A peer discovered on the local network.
class LanPeer {
  final String peerId;

  const LanPeer({required this.peerId});

  @override
  int get hashCode => peerId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LanPeer &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId;
}
